In [ ]:
# 1 and 2 shell represents the array and list in python
import numpy as np
x=np.array([1,2,3,5])
print(x)
print(type(x))
print(np.__version__)

[1 2 3 5]
<class 'numpy.ndarray'>
1.25.2


In [ ]:
y=[1,2,3,4]
print(y)
print(type(y))

# Difference between list and array
# same type of values are only allowed in array while a list can accumulate different types

[1, 2, 3, 4]
<class 'list'>


In [ ]:
%%timeit  # it will display the time taken for the execution of the whole code
# getting the time difference
import numpy as np
%timeit x = np.array([1,2,3,4]) # display the time taken by a single line
%timeit x = list([1,2,3,4])

1.02 µs ± 307 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
164 ns ± 5.79 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
785 ns ± 6.22 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
182 ns ± 39.1 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
974 ns ± 321 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
181 ns ± 39.7 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
996 ns ± 316 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
181 ns ± 37.7 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
799 ns ± 12.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
178 ns ± 36.1 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
790 ns ± 8.43 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
181 ns ± 41 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
997 ns ± 313 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
180 ns ± 36.1 ns per loop

In [ ]:
x=np.arange(1,9,0.4) # arrange function provides us an array from the starting to the ending point work almost same as range function
print(x)

# Decimal steps are also allowed in arange while not so in range only integer steps can be taken

[1 2 3 4 5 6 7 8]


In [ ]:
# Creating numpy array
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(type(x))
x   # writing x only makes it clear that x is an array

[1 2 3 4]
<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [ ]:
# we can also directly import array from numpy
import numpy as np
from numpy import array
x=array([1,2,3,4])
print(x)

[1 2 3 4]


In [ ]:
 # when we want the user to decide the elements of array
 import numpy as np
 l=[]
 for i in range(1,5):
  int_1=int(input("Enter no:")) #if we don't write int here then we will get the input as strings
  l.append(int_1)
print(np.array(l))

Enter no:23
Enter no:12
Enter no:34
Enter no:45
[23 12 34 45]


In [ ]:
# how to get the dimension of the array
#for that we will use ndim function
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(x.ndim) # it shows the dimension of the array

[1 2 3 4]
1


In [ ]:
# Creating 2-D array
import numpy as np
x=np.array([[1,2,3,4],[2,3,4,5]]) # here we can enter single list also or more than 2 lists but it should be kept in mind that the no of elements in every list must be same
y=np.array([[1,2,3,5]])
z=np.array([[1,2,3,4],[2,3,4,5],[4,54,4,5]])
print(x)
print(x.ndim)
print(y)
print(y.ndim)
print(z)
print(z.ndim)

[[1 2 3 4]
 [2 3 4 5]]
2
[[1 2 3 5]]
2
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 4 54  4  5]]
2


In [ ]:
# creating 3D array
import numpy as np
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(x.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [ ]:
# creating more dimensional array
import numpy as np
x=np.array([1,2,3,4] , ndmin=2)
print(x)
print(x.ndim)
print(x.shape)

print(np.array([1,2,3,4]))

[[1 2 3 4]]
2
(1, 4)
[1 2 3 4]


In [ ]:
# Creating array with all elements as 0 with zeros function
import numpy as np
x=np.zeros(4)
print(x)
y=np.zeros((3,2)) # the values represent rows and columns respectively
print()
print(y)
print(y.ndim)

[0. 0. 0. 0.]

[[0. 0.]
 [0. 0.]
 [0. 0.]]
2


In [ ]:
# Creating array with all elements as 1 using ones function
import numpy as np
x=np.ones(2)
print(x)
y=np.ones((3,4))
print(y)
print(y.ndim)

[1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2


In [ ]:
# Creating an empty array using empty function
import numpy as np
a=np.empty(3)
print(a) # output will be the values already present and empty function will not give any new value

[1. 1. 1.]


In [ ]:
# Creating an array based on range values using arange function
import numpy as np
x=np.arange(4,12)
print(x)
print()
print(x.ndim)

[ 4  5  6  7  8  9 10 11]

1


In [ ]:
# Creating an identity matrix using eye function
import numpy as np
x=np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# creating an array with values that are spaced linearly with specific intervals using linspace function
import numpy as np
x=np.linspace(1,20,7)
print(x)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [ ]:
# Creating numpy array using random function

In [ ]:
# (rand function) create a random number between 0 and 1 only  (0,1]
import numpy as np
#1-D array is created
x=np.random.rand(5)
print(x)
print(x.ndim)
#2-D array is created
y=np.random.rand(3,4)
print(y)
print(y.ndim)

[1.27656203e-01 6.71361292e-04 4.51844798e-01 5.25837904e-01
 9.76193446e-01]
1
[[0.95321499 0.59276247 0.13487011 0.66329936]
 [0.07545707 0.42201949 0.95817599 0.84784069]
 [0.60034355 0.09712127 0.92845495 0.91007845]]
2


In [ ]:
# (randn function) create a random no very close to 0 may be +ve or -ve
import numpy as np
x=np.random.randn(5)
print(x)
print(x.ndim)
y=np.random.randn(3,5)
print(y)
print(y.ndim)

[-1.18719607  0.35335979 -0.19474105 -1.6272101  -1.52210457]
1
[[ 0.57531836  0.31926032  1.2686248  -0.81730008  0.01765461]
 [ 0.55545326  0.27707343 -0.09204834 -1.13165223 -1.68396587]
 [-0.8086438   0.23746716 -0.62885272 -1.05633799  1.18047822]]
2


In [ ]:
# (ranf function) generate a random number between 0 and 1 but 1 is not included this time  (0,1)
import numpy as np
x=np.random.ranf(5)
print(x)

[0.71370388 0.72548074 0.60060688 0.21969774 0.25177135]


In [ ]:
# (randint function) generate a random number between any two values and we can also specify the number of values that we want in between them
x=np.random.randint(2,30,4)
# 2 defines the starting value 30 the last value and 4 is the no of values that we want in between these values
print(x)
print(x.ndim)

[15 25 15 22]
1


In [ ]:
# Determination of Datatype

In [ ]:
# we use dtype function to determine the data type of array
x=np.array([1,2,3,4])
print(x.dtype)
y=np.array([2,3,4,5.9,5.6])
print(y.dtype)
z=np.array(["a","c","d"])
print(z.dtype) # in the output U1 shows string data type

int64
float64
<U1


In [ ]:
# Conversion from one data type to another

In [ ]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
x=np.array([1,2,3,4],dtype=np.float64)
print(x.dtype)
print(x)

[1 2 3 4]
float64
[1. 2. 3. 4.]


In [ ]:
x=np.array([1,2,3,4],dtype='B')
print(x.dtype)
print(x) # in the output b represents byte literal

uint8
[1 2 3 4]


In [ ]:
# Datatype as function
x=np.array([1,2,3,4])
print(x)
print(x.dtype)
print()
new=np.float64(x)
print(new)
print(new.dtype)
print()
new_1=np.int64(new)
print(new_1)
print(new_1.dtype)

[1 2 3 4]
int64

[1. 2. 3. 4.]
float64

[1 2 3 4]
int64


In [ ]:
# using astype function we can do conversion
import numpy as np
x=np.array([1,2,3,4])
print(x)
y=x.astype(float)
print(y)
print(y.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
float64


In [ ]:
# Arithmetic operations in Numpy

In [ ]:
# Addition
# To add a particular no to all the elements of an array
import numpy as np
x=np.array([1,2,3,4])
y=x+3
print(y)
# using function it will be like
print()
y=np.add(x,3)
print(y)
# To add two arrays
z=np.array([2,4,5,7])
s=x+z
# it will result in adding the corresponding values
print()
print(s)
# Using function
print()
y=np.add(x,z)
print(y)
# for 2D array
print()
x=np.array([[1,2,3,4],[2,3,4,5]])
y=np.array([[2,3,4,5],[5,6,7,8]])
z=x+y
print(z)

[4 5 6 7]

[4 5 6 7]

[ 3  6  8 11]

[ 3  6  8 11]

[[ 3  5  7  9]
 [ 7  9 11 13]]


In [ ]:
# Subtraction
# To subtract a particular no from all the elements of an array
import numpy as np
x=np.array([1,2,3,4])
y=x-3
print(y)
# To subtract two arrays
z=np.array([2,4,5,7])
s=x-z
# it will result in subtracting the corresponding values
print(s)
# using function
y=np.subtract(x,z)
print(y)
print()
# for 2D array
x=np.array([[1,2,3,4],[2,3,4,5]])
y=np.array([[2,3,4,5],[5,6,7,8]])
z=x-y
print(z)

[-2 -1  0  1]
[-1 -2 -2 -3]
[-1 -2 -2 -3]

[[-1 -1 -1 -1]
 [-3 -3 -3 -3]]


In [ ]:
# Multiplication
# To multiply particular no to all the elements of an array
import numpy as np
x=np.array([1,2,3,4])
y=x*3
print(y)
# To multiply two arrays
z=np.array([2,4,5,7])
s=x*z
# it will result in multiplying the corresponding values
print(s)
# using function
y=np.multiply(x,z)
print(y)
# for 2D array
print()
x=np.array([[1,2,3,4],[2,3,4,5]])
y=np.array([[2,3,4,5],[5,6,7,8]])
z=x*y
print(z)

[ 3  6  9 12]
[ 2  8 15 28]
[ 2  8 15 28]

[[ 2  6 12 20]
 [10 18 28 40]]


In [ ]:
# Division
# To divide a particular no from all the elements of an array
import numpy as np
x=np.array([3,6,9,12])
y=x/3
print(y)
# To divide two arrays
z=np.array([1,2,3,4])
s=x/z
# it will result in dividing the corresponding values
print(s)
# using function
y=np.divide(x,z)
print(y)
# for 2D array
print()
x=np.array([[1,2,3,4],[2,3,4,5]])
y=np.array([[2,3,4,5],[5,6,7,8]])
z=x/y
print(z)

[1. 2. 3. 4.]
[3. 3. 3. 3.]
[3. 3. 3. 3.]

[[0.5        0.66666667 0.75       0.8       ]
 [0.4        0.5        0.57142857 0.625     ]]


In [ ]:
# modulus
# To divide a particular no from all the elements of an array and giving the remainder
import numpy as np
x=np.array([1,2,3,4])
y=x%3
print(y)
# To divide two arrays and produce the remainder
z=np.array([4,5,6,7])
s=x%z
# it will result in dividing the corresponding values and then producing the remainder
print(s)
# using function
y=np.mod(x,z)
print(y)
# for 2D array
print()
x=np.array([[1,2,3,4],[2,3,4,5]])
y=np.array([[2,3,4,5],[5,6,7,8]])
z=x%y
print(z)

[1 2 0 1]
[1 2 3 4]
[1 2 3 4]

[[1 2 3 4]
 [2 3 4 5]]


In [ ]:
# Power
# To raise to the power of each element with a particular number
import numpy as np
x=np.array([3,6,9,12])
y=x**3
print(y)
# for two arrays
z=np.array([1,2,3,4])
s=x**z
# it will raise to the power to each corresponding element
print(s)
# using function
y=np.power(x,z)
print(y)
# for 2D array
print()
x=np.array([[1,2,3,4],[2,3,4,5]])
y=np.array([[2,3,4,5],[5,6,7,8]])
z=x**y
print(z)

[  27  216  729 1728]
[    3    36   729 20736]
[    3    36   729 20736]

[[     1      8     81   1024]
 [    32    729  16384 390625]]


In [ ]:
# Reciprocal
import numpy as np
x=np.array([3,6,9,12])
y=1/x
print(y)
z=np.array([1,2,3,4])
s=x/z
t=1/s
print(t)
# using function
y=np.reciprocal(s)
print(y)
# for 2D array
print()
x=np.array([[1,2,3,4],[2,3,4,5]])
y=np.array([[2,3,4,5],[5,6,7,8]])
z=x/y
t=1/z
print(t)

[0.33333333 0.16666667 0.11111111 0.08333333]
[0.33333333 0.33333333 0.33333333 0.33333333]
[0.33333333 0.33333333 0.33333333 0.33333333]

[[2.         1.5        1.33333333 1.25      ]
 [2.5        2.         1.75       1.6       ]]


In [ ]:
# Arithmetic Functions

In [ ]:
import numpy as np
x=np.array([1,2,3,4])
# max function
print(np.max(x))
# for 2D array
y=np.array([[1,2,3],[3,4,5]])
print(np.max(y,axis=1))
print(np.max(y,axis=0))
# min function
print(np.min(x))
# for 2D array
print(np.min(y,axis=1))
print(np.min(y,axis=0))
# sqrt function
z=np.array([1,4,9,16],dtype='i')
print(np.sqrt(z))
print(np.sqrt(y))
# sin function
print(np.sin(z))
print(np.sin(y))
# cos function
print(np.cos(z))
print(np.cos(y))
# cumsum function (cumulative sum i.e. it is almost same as fibonacci series)
print(np.cumsum(z))
print(np.cumsum(y))

4
[3 5]
[3 4 5]
1
[1 3]
[1 2 3]
[1. 2. 3. 4.]
[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[[ 0.84147098  0.90929743  0.14112001]
 [ 0.14112001 -0.7568025  -0.95892427]]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.9899925  -0.65364362  0.28366219]]
[ 1  5 14 30]
[ 1  3  6  9 13 18]


In [ ]:
# To get the position of maximum and minimum value we use argmin and argmax function respectively
import numpy as np
x=np.array([1,2,3,4])
print(np.argmax(x))
print(np.argmin(x))


3
0


In [ ]:
 #shape and reshape of numpy array

In [ ]:
# Shape function
import numpy as np
x=np.array([[1,2,3,4],[2,3,4,5]])
print(x)
print(x.shape)
# for multidimensional array
y=np.array([1,2,3,4],ndmin=12)
print(y)
print(y.shape)

[[1 2 3 4]
 [2 3 4 5]]
(2, 4)
[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]
(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


In [ ]:
# reshape function
import numpy as np
x=np.array([1,2,3,4])
print(x.reshape(2,2))
print()
# for 3D array
y=np.array([1,2,3,4,5,6,1,2,3,4,5,6])
# first two represents the no of rows that are being separated out here second 2 represents the no. of rows inside each row and 3 represents no of elements in each row
z=y.reshape(2,2,3)
print(z)
# Converting to 1D array
print()
print(z.reshape(-1))

[[1 2]
 [3 4]]

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

[1 2 3 4 5 6 1 2 3 4 5 6]


In [ ]:
"""Broadcasting
when we try to add two arrays not having same dimensions we get broadcast error and to solve that there are two conditions either we should
make the dimensions equal or compare them and if both have one 1 then the condition of broadcasting is applicable
__ the arrays will be of the dimension of the number other than 1 eg:- the arrays are of 1*3 and 3*1 then the final array will be of 3*3"""

In [ ]:
import numpy as np
x=np.array([1,2,3,4,6])
print(x)
y=np.array([[1],[2],[3]])
print()
print(y)
print()
print(x+y)

[1 2 3 4 6]

[[1]
 [2]
 [3]]

[[2 3 4 5 7]
 [3 4 5 6 8]
 [4 5 6 7 9]]


In [ ]:
# indexing

In [ ]:
# for 1-D
import numpy as np
x=np.array([1,2,3,4])
print(x[1])
# -ve indexing
print(x[-2])
# for 2-D
y=np.array([[1,2,3,4],[5,6,7,8]])
print(y[0,3])
# -ve indexing
print(y[-1,-3])
# for 3-D
z=np.array([[[1,2,3,4],[6,7,8,9]],[[4,3,2,1],[5,6,7,8]]])
print(z[1,0,1])
# -ve indexing
print(z[-1,-1,-1])


2
3
4
6
3
8


In [ ]:
# Slicing

In [ ]:
# For 1-D
import numpy as np
x=np.array([1,2,3,4])
print(x[1:3])
print(x[-3:-1])
print(x[1:])
print(x[:2])
# taking more than one step
print(x[::2])
print(x[1::2])
# for 2-D
y=np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])
print(y[1,1:])
print(y[-1,1:])
print(y[1,0:4:2])
# for 3-D
z=np.array([[[1,2,3,4],[5,6,7,8],[9,7,6,5]]])
print(z)
print()
print()
print()
print()
print()
print(z[0,1,:2])
print(z[-1,-2,1:])
print(z[0,1,0:4:2])
# to grab everything in the slice
print(z[:])
# we can also change the value
z[:]=44
print(z)
# if we want to have a sub-array in output
print(z[1:,:2])

[2 3]
[2 3]
[2 3 4]
[1 2]
[1 3]
[2 4]
[6 7 8]
[8 7 6]
[5 7]
[[[1 2 3 4]
  [5 6 7 8]
  [9 7 6 5]]]





[5 6]
[6 7 8]
[5 7]
[[[1 2 3 4]
  [5 6 7 8]
  [9 7 6 5]]]
[[[44 44 44 44]
  [44 44 44 44]
  [44 44 44 44]]]
[]


In [ ]:
#Iteration

In [ ]:
# 1-D
import numpy as np
x=np.array([1,2,3,4])
for i in x:
  print(i)

1
2
3
4


In [ ]:
# 2-D
import numpy as np
x=np.array([[1,2,3,4],[4,5,6,7]])
for i in x :
  print(i)
print()
for j in x:
  for k in j:
    print(k)

[1 2 3 4]
[4 5 6 7]

1
2
3
4
4
5
6
7


In [ ]:
# 3-D
import numpy as np
x=np.array([[[1,2,3,4],[5,6,7,8]]])
for i in x:
  print(i)
print()
for j in x:
  for k in j:
    print(k)
print()
for i in x:
  for j in i:
    for k in j:
      print(k)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [ ]:
# to reduce time complexity use nditer function
import numpy as np
x=np.array([[1,2,3,4],[2,3,4,5]])
for i in np.nditer(x):
  print(i)

1
2
3
4
2
3
4
5


In [ ]:
# using flags to store data and the required data type to be string
import numpy as np
x=np.array([1,2,3,4])
for i in np.nditer(x,flags=['buffered'],op_dtypes=['S']):
  print(i)
# in the output b shows byte format



b'1'
b'2'
b'3'
b'4'


In [ ]:
# to get the index along with the data
import numpy as np
x=np.array([[1,2,3,4],[5,6,7,8]])
for i,d in np.ndenumerate(x):
  print(i,d)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [ ]:
# Copy v/s View

In [ ]:
# Copy
import numpy as np
x=np.array([1,2,3,4])
co=x.copy()
co[2]=5
print("var:" , x)
print("copy:" , co)

var: [1 2 3 4]
copy: [1 2 5 4]


In [ ]:
# View
import numpy as np
x=np.array([1,2,3,4])
vi=x.view()
x[2]=5
print("view:" , vi)

# Difference between copy and view
# when made changes using copy the original array does not get affected while in view the original array gets affected only

view: [1 2 5 4]


In [ ]:
# To join two arrays using concatenate and stack function and make a new array

In [ ]:
# for 1-D
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.concatenate((x,y))
print(z)
# for 2-D
a=np.array([[[1,2],[3,4]]])
b=np.array([[[5,6],[7,8]]])
c=np.concatenate((a,b),axis=0)
print()
print(c)
d=np.concatenate((a,b),axis=1)
print()
print(d)
print()

f=np.concatenate((a,b),axis=2)
print(f)
print()

g=np.concatenate((a,b),axis=0)
print(g)

[1 2 3 4 5 6 7 8]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]

[[[1 2 5 6]
  [3 4 7 8]]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Stack function
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
z=np.stack((x,y),axis=1)
print(z)
a=np.stack((x,y),axis=0)
print()
print()
print(a)

# Difference between concatenate and stack

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# hstack function for joining along row
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
z=np.hstack((x,y))
print(z)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# vstack function for joining along column
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
z=np.vstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# dstack function for joining along height
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
z=np.dstack((x,y))
print(z)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [ ]:
# split function

In [ ]:
# for 1-D
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.split(x,3)
print(y)
print(type(y))
print(y[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[5 6]


In [ ]:
# for 2-D
import numpy as np
x=np.array([[1,2],[3,4],[5,6],[3,5],[6,7],[1,9]])
y=np.split(x,2, axis = 1)
print(y)

[array([[1],
       [3],
       [5],
       [3],
       [6],
       [1]]), array([[2],
       [4],
       [6],
       [5],
       [7],
       [9]])]


In [ ]:
# functions in Numpy Arrays

In [ ]:
# where function for search
import numpy as np
x=np.array([1,2,3,4,2,4,6,2,4,2])
y=np.where( x==2)
print(y)
# here we can also specify any function like
z=np.where(x%2==0)
print(z)

(array([1, 4, 7, 9]),)
(array([1, 3, 4, 5, 6, 7, 8, 9]),)


In [ ]:
# search sorted function for getting the position of the element to be placed in a sorted array
import numpy as np
x=np.array([1,2,3,4,6,7,8,9,10])
y=np.searchsorted(x,5)
print(y)
# if we want to get the index from the right hand side we can use side
z=np.searchsorted(x,8,side='right')
print(z)

4
7


In [ ]:
# Sort function to sort an array
import numpy as np
x=np.array([2,4,1,3,9,6,8,7])
y=np.sort(x)
print(y)
# 2_D array
d=np.array([[1,5,3],[4,2,5]])
e=np.sort(d)
print(e)
# alphabets
a=np.array(['f','r','a','w','u'])
b=np.sort(a)
print(b)

[1 2 3 4 6 7 8 9]
[[1 3 5]
 [2 4 5]]
['a' 'f' 'r' 'u' 'w']


In [ ]:
# filter array (to get some elements from existing array and creating a new array out of them)
import numpy as np
x=np.array([1,2,3,5])
f=[True,False,True,False]
d=x[f]
print(d)
print(d.dtype)

[1 3]
int64


In [ ]:
# Shuffle function to change the arrangement of array
import numpy as np
x=np.array([1,2,3,4,5])
np.random.shuffle(x)
print(x)

[4 3 1 5 2]


In [ ]:
# Unique function
# to get the unique elements from an array containing repetitive elements
import numpy as np
x=np.array([1,2,3,4,3,2,2,3,2,4,5])
y=np.unique(x,return_index=True,return_counts=True)
print(y)

(array([1, 2, 3, 4, 5]), array([ 0,  1,  2,  3, 10]), array([1, 4, 3, 2, 1]))


In [ ]:
# Resize Function
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.resize(x,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Flatten function ( to convert from 2-D to 1-D array or say any dimensional array to 1D)
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x.flatten())
print()
print(x.flatten(order='C'))
print()
print(x.flatten(order='F'))
print()
print(x.flatten(order='A'))
print()
print(x.flatten(order='K'))

[1 2 3 4 5 6]

[1 2 3 4 5 6]

[1 4 2 5 3 6]

[1 2 3 4 5 6]

[1 2 3 4 5 6]


In [ ]:
# Ravel Function
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x.ravel())
print()
print(x.ravel(order='C'))
print()
print(x.ravel(order='F'))
print()
print(x.ravel(order='A'))
print()
print(x.ravel(order='K'))

[1 2 3 4 5 6]

[1 2 3 4 5 6]

[1 4 2 5 3 6]

[1 2 3 4 5 6]

[1 2 3 4 5 6]


In [ ]:
# Insertion

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.insert(x,2,30)
print(y)

[ 1  2 30  3  4  5  6]


In [ ]:
# when we want to insert same value at multiple position
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.insert(x,(2,4),30)
print(y)


[ 1  2 30  3  4 30  5  6]


In [ ]:
# trying to imsert float value will only take integer part
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.insert(x,(2,4),3.5)
print(y)

[1 2 3 3 4 3 5 6]


In [ ]:
# Insertion for 2-D array
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
y=np.insert(x,2,3.5,axis=1)
print(y)
z=np.insert(x,2,(3.5,4,5),axis=0)
print()
print(z)
a=np.insert(x,2,3.5,axis=1)
print()
print(a)

[[1 2 3 3]
 [4 5 3 6]]

[[1 2 3]
 [4 5 6]
 [3 4 5]]

[[1 2 3 3]
 [4 5 3 6]]


In [ ]:
# Append function
import numpy as np
x=np.array([1,2,3,4,5])
y=np.append(x,6)
print(y)
# 2-D
a=np.array([[1,2,3],[4,5,6]])
#b=np.append(a,2)
#print(b)
d=np.array([[2],[3],[4]])
c=np.append(a,d,axis=1)
print(c)

[1 2 3 4 5 6]


ValueError: ignored

In [ ]:
# Deletion

In [ ]:
import numpy as np
x=np.array([1,2,3,4])
y=np.delete(x,3)
print(y)

[1 2 3]


In [ ]:
# Matrix

In [ ]:
# Creating matrix
import numpy as np
x=np.matrix([[1,2,3],[4,5,6]])
print(x)
print()
y=np.array([[1,2,3],[4,5,6]])
print(y)
print()
print(type(x))
print(type(y))

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]

<class 'numpy.matrix'>
<class 'numpy.ndarray'>


In [ ]:
# difference between matrix and numpy array
--no difference in addition

In [ ]:
# matrix multiplication
# .dot function is used for the same
import numpy as np
x=np.matrix([[1,2,3,4]])
print(x.shape)
y=np.matrix([[1],[2],[3],[4]])
print(y.shape)
print()
print(x.dot(y))

(1, 4)
(4, 1)

[[30]]


In [ ]:
# Matrix functions in numpy arrays
# Transpose of a matrix
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x)
print()
print(np.transpose(x))
# transpose using shortcut
print()
print(x.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# swapaxes function
import numpy as np
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print()
print(np.swapaxes(x,0,1))

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
# inverse function
import numpy as np
x=np.array([[1,2],[5,6]])
print(x)
print()
print(np.linalg.inv(x))

[[1 2]
 [5 6]]

[[-1.5   0.5 ]
 [ 1.25 -0.25]]


In [ ]:
# Power of a matrix
import numpy as np
x=np.matrix([[1,2],[3,4]])
print(x)
print()

print(np.linalg.matrix_power(x,0))
print()
print(np.linalg.matrix_power(x,-2))
print()
print(np.linalg.matrix_power(x,2))

[[1 2]
 [3 4]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]

[[ 7 10]
 [15 22]]


In [ ]:
# determinant of a matrix
import numpy as np
x=np.matrix([[1,2],[3,4]])
print(x)
print()
print(np.linalg.det(x))

[[1 2]
 [3 4]]

-2.0000000000000004


In [ ]:
# Comparison between array and list

In [ ]:
# array takes less memory than a list
#sys library
import numpy as np
import sys
u=range(1000)
print(sys.getsizeof(u)) # this method is used to get the memory size of u
print(sys.getsizeof(len(u))) # here the memory size of len(u)
# to get the memory address of an array
import numpy as np
a=np.array([1,2,3,4,5])
print(a.size*a.itemsize)

48
28
40


In [2]:
# boolean function
import numpy as np
a=np.array([1,2,3,4,5])
print(a<3)
# we can also get the value directly
print(a[a<3])

[ True  True False False False]
[1 2]


In [ ]:
# Statistical operations

In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
print(np.mean(A))
print(np.mean(A[0:3]))
print(np.median(A))
# correlation
print(np.corrcoef(A[0:2],A[1:3]))
# Standard Deviation
print(np.std(A[1:]))
# Variance
print(A.var())

3.0
2.0
3.0
[[1. 1.]
 [1. 1.]]
1.118033988749895
2.0


In [ ]:
# Practice problems

In [ ]:
import numpy as np
from numpy import array
a=np.zeros(10)
print(a)
b=np.ones(10)
print(b)
a[:]=5
print(a)
c=np.arange(10,51)
z=c[c%2==0]
print(z)
d=np.eye(3,3)
print(d)
e=np.random.rand(1)
print(e)
f=np.random.randn(25).reshape(5,5)
print(f)
g=np.linspace(0,1,100).reshape(10,10)
np.set_printoptions(precision=2)
print(g)
h=np.linspace(0,1,20).reshape(4,5)
print(h)

In [ ]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
print(a)
b=np.std(a)
for i in a[,0:]:
  print(sum)

SyntaxError: ignored

In [ ]:
import numpy as np
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
z=np.array([[[1,2,3,4],[5,6,7,8],[9,7,6,5]]])
print(z[0,1,1:])

[6 7 8]
